### ISSUE TITLE
Tests Unimplemented after upgrading to 17.1

### ISSUE THREAD

**Issue by Emibob** [calabash/calabash-ios#1000]
I was able to run my feature tests using Calabash 16.3. However now that I've updated to 17.1 when I run my tests it seems as though everything is unimplemented. Tried reinstalling the framework. Not sure what else I can try?

**Comment by jmoody** [comment]
Please update to 0.18.0 or wait a few hours and update to 0.18.1.

Can you describe what you mean by "unimplemented"?  Is there a specific error message?  What Xcode version are you using?

**Comment by jmoody** [comment]
Please update to 0.18.1.  If you are still having problems, we can reopen this issue.

**Comment by Emibob** [comment]
@jmoody sorry for the delay, I got moved onto a different story for a while. I just updated to 0.18.1 & am still having the same problem.

Using XCode 7.2.1

The error is that none of my steps seem to be defined after I upgrade. Everything had been passing when I used 0.16.4 & now I'm getting:

![screen shot 2016-03-03 at 1 32 42 pm](https://cloud.githubusercontent.com/assets/4623303/13504667/79c264ee-e143-11e5-9065-e19a61a2bcc7.png)

Other than that I'm not getting any error messages. Here's some more context:
![screen shot 2016-03-03 at 1 34 37 pm](https://cloud.githubusercontent.com/assets/4623303/13504726/c00cd006-e143-11e5-8e37-9e81211be142.png)

**Comment by jmoody** [comment]
We recently relaxed the cucumber dependency to allow cucumber 2.0.

My guess is that your setup is not compatible with cucumber 2.0.

Try forcing cucumber 1.3:

```
gem "cucumber", "~> 1.13"
```

and run again.

Your setup looks a bit complex so it is hard for me to analyze.  Are you using a cucumber configuration file?   Please try to run the tests with `cucumber` alone so you can isolate the problem.

I don't think this has anything to do with Calabash.  There is a problem with your setup.

**Comment by Emibob** [comment]
@jmoody it looks like the issue is actually that I'm now unable to autodetect the app where I was able to before. Running `APP=/Users/emily.obrien/Library/Developer/Xcode/DerivedData/ThisAm-gygrlhcderyepmbdofmmhnwaibuz/Build/Products/Debug-iphonesimulator/thisAM-cal.app RESET_BETWEEN_SCENARIOS=1 DEVICE_TARGET="iPhone 5s (9.2)" cucumber` will run my tests without failure however would like to be able to run these without hard coding the built app. Is this possible?

**Comment by jmoody** [comment]
Just to be clear, the issue you reported (undefined steps) is not because the app cannot be found.

> Is this possible?

Are you sure you are using 0.18.1?  We did a fair amount of work to try to automatically detect the .app after it was broken (for many users) by #704.

I don't recommend relying on the automatic detection.  I recommend doing one of the following:

### Use scripts

1. Build with scripts and stage the .app and .ipa to a known (local) directory.
2. Add Xcode Run Script build phases to stage binaries to the directory as **1.**

Here are examples:

* https://github.com/calabash/ios-smoke-test-app/tree/master/CalSmokeApp
* https://github.com/calabash/Permissions 

### Update your Xcode > Settings > Location settings

Using the Location settings you can specify a local directory for binaries.

![image](https://cloud.githubusercontent.com/assets/466104/13537701/70d07fe8-e246-11e5-850c-3644cd357dbd.png)
