### ISSUE TITLE
calabash-ios  -shell script to build calabash apps from source code.

### ISSUE THREAD

**Issue by eearif** [calabash/calabash-ios#1041]
@jmoody 
please provide a shell script when used with the xcode source code and provide -cal name of app
will create the calabash app and store in a particular folder by itself.
why are these steps manual so far ?? 

can you please explain why calabash-ios is slowly becoming outdated and redundant;
there was a time when appium was struggling with ios and it was a big pain . Now they are providing much better features and functionalities for both apps and mobile web support .
Why is calabash -ios behind, can u please discuss the roadmap and ramp up the speed .
Please let us know , as we are highly dependant on calabash-ios .

**Comment by krukow** [comment]
@eearif - Your comment is plain wrong and not appreciated. Your message is pure [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt). Touches, swipes and all gestures work as do all other features in Calabash. Calabash is neither outdated nor redundant, in-fact Calabash has been more active than appium over the last few months ([Appium commits](https://github.com/appium/appium/graphs/commit-activity) vs [Calabash iOS commits](https://github.com/calabash/calabash-ios/graphs/commit-activity) although while comparing commits isn't very meaningful it does say something about activity). 

Calabash is not lagging behind, but is accelerating: we're close to a major 2.0 release and we're building out new very powerful features as part of that.

I'm not sure what your intent is with these comments, but I consider them malicious and non constructive. 
If you are experiencing issues please just create a new issue rather than hijacking an existing different issue. Please follow the guide for reporting issues (with examples of good reports): https://github.com/calabash/calabash-ios/wiki#reporting-problems 

If you want to test pure browser web-apps use Appium, Calabash is targeting web apps.

If you're looking for a roadmap please see:

https://groups.google.com/d/msg/calabash-ios/KeamyYqVHNQ/mx9TGg-B700J 
and note that we're working XCUITest support.
