### ISSUE TITLE
Non-public API Usage - can you, you know, stop doing this?

### ISSUE THREAD

**Issue by skydivedan** [calabash/calabash-ios#1100]
Relatively new to Calabash. We got busted by Apple for using non-public API usage. Found it it was Calablash.

Then, I see this entry on your website, explaining that this is intentional:
https://developer.xamarin.com/guides/testcloud/troubleshooting/#The_Apple_App_Store_Rejected_My_iOS_App_Because_of_Non-public_API_Usage

It seems like it's been this way for over a year. But, seriously? Is there no way for this product to function otherwise? Sorry to sound incredulous here, but it would be really great if this wasn't using undocumented APIs at all, you know?

**Comment by jmoody** [comment]
Calabash has used private APIs since its inception.  There is no way for Calabash to function without using the private APIs.  Calabash's embedded server is a very powerful UI Automation tool - its power is its advantage.

At various times, warnings about not including Calabash in app store submissions have been in our README.  In recent memory, I removed this information from the README in an attempt to make the front page more digestible.   After a quick look at our wiki pages and README, I think we need to be more explicit about this.

Closing this issue in favor of https://github.com/calabash/calabash-ios/issues/725

Thank you for reporting.
