### ISSUE TITLE
No longer possible to pass Environment variables to instance

### ISSUE THREAD

**Issue by Holloweye** [calabash/calabash-ios#1172]
I have been doing the following for a while:

options[:args] = [ '-e', 'USER_DATA', '<info>' ]
launcher.relaunch(options)

It worked great for over a year but since I updating XCode8 + Calabash it no longer works. The environment variable can't be found in NSProcessInfo.

**Comment by jmoody** [comment]
That was a feature of `instruments`.  It is not clear how we can support this without instruments.

If there were a server route to set an environment variable, would that work?  Can you describe your use case?

For iOS Simulators, we _might_ be able to use `simctl` to set an env variable on launch.

```
$ xcrun simctl help launch
Usage: simctl launch [-w | --wait-for-debugger] <device> <app identifier> [<argv 1> <argv 2> ... <argv n>]

If you want to set environment variables in the resulting environment, set them in the calling environment with a SIMCTL_CHILD_ prefix.
```

**Comment by Holloweye** [comment]
I use this method to skip the login flow for many of the tests. I use a tag "@user_logged_in" that will before the scenario starts Base64 encode a user.json and pass it as environment variable over to the simulator. Which then later the app at "DidFinishLaunchingWithOptions.." read and store in the documents folder of the app. Which simulates a logged in user. I use this method to speed up tests without having to do "Given user is logged in" and then do the login flow each time.

**Comment by Holloweye** [comment]
If anyone is having a similar problem I solved my issue by using `set_user_pref(key, value)` instead, works like a charm. And then adding a observer on NSUserDefaults to switch to userflow whenever the specific key was set to "loggedin".

**Comment by jmoody** [comment]
@Holloweye Thank you for sharing!

**Comment by daniele-xp** [comment]
Hi!
I have the same problem, has anyone found a solution?
Is it still possible to pass and environment variable to the simulator?

**Comment by daniele-xp** [comment]
It is probably related to this issue on run_loop (?) https://github.com/calabash/run_loop/issues/178

**Comment by jmoody** [comment]
@daniele-xp This is a new problem.  #178 has been closed for some time.

Calabash no longer uses `instruments` to launch the application so environment variables are not set.

**Comment by daniele-xp** [comment]
@jmoody So it's a _calabash_ issue and not a _run_loop_ issue? When did it changed?

Thank you for your suppport

**Comment by jmoody** [comment]
I would classify this as an Xcode issue.  Starting in Xcode 8, there is no UIAutomation.  When using UIAutomation, applications are launched with `instruments`.  Without UIAutomation, we had to invent a replacement:  DeviceAgent.  Launching apps with arguments and environment variables has not been implement in our DeviceAgent implementation.

> Calabash vs run_loop

Calabash is the ruby Cucumber API for the Calabash iOS BDD framework.  Run_loop is the bridge between Calabash and the Apple tools.  I recommend that you think of Calabash iOS and run-loop as the same product - the split exists because the ruby Cucumber API is mostly stable, but Apple's tools are constantly changing.

**Comment by daniele-xp** [comment]
Thank you @jmoody 

Do you think that launching apps with environment variables will be implemented in the next versions of DeviceAgent?

Otherwise, how can we obtain the same purpose (change app behaviour from tests) with DeviceAgent now?

**Comment by jmoody** [comment]
> next version

Any fix will be weeks from now.

> workaround

Use a backdoor or the Calabash NSUserDefaults API.

**Comment by jmoody** [comment]
We think we have a solution, but it will be a few weeks before we can add the client code to support this.  IIRC, we never officially supported setting instruments environment variables - we did support launching applications with _arguments_.

**Comment by daniele-xp** [comment]
Thank you @jmoody, it would be great!
Yes it's true, that is the correct way to describe the feature.

**Comment by JoeSzymanski** [comment]
We would like to know any details possible. The NSUserDefaults case isn't possible for us, as we have  actions that occur on launch, prior to having a valid connection from Calabash to run the NSUserDefaults commands. Are there any workarounds otherwise for this issue?

**Comment by JoeSzymanski** [comment]
@jmoody Are there any updates on this timeline? We don't need environment variables, but we do need some way to launch our app with arguments. This is blocking us from upgrading Xcode, iOS, and Calabash, since we have functionality that must be touched prior to the Calabash API connecting to the device.

**Comment by jmoody** [comment]
I have a rough implementation and demonstrated that it works.  This feature is in progress and will be available in an up coming _run-loop_ release.

**Comment by TheChell** [comment]
Any word on this?

**Comment by JoeSzymanski** [comment]
Any updates? We're reaching the point that this limitation is causing us to have to abandon testing of certain aspects of our application until some fix is in place.

**Comment by jmoody** [comment]
Fix will be available in run-loop 2.2.3.

**Comment by jmoody** [comment]
@Holloweye @JoeSzymanski @TheChell @daniele-xp 

Please see the examples in https://github.com/calabash/run_loop/pull/567

**Comment by TheChell** [comment]
@jmoody, can't tell you how happy our team is that Calabash 0.20.4 is out. 

I see that **DA:Client: launch AUT with args and environment** (Issue: https://github.com/calabash/run_loop/pull/567) is in the changelog for _run_loop 2.2.3_. However, the changelog for _Calabash 0.20.4_ mentions run_loop _2.2.2_. 

Since run_loop 2.2.2 has been out for a while, I'm hoping this is just a typo? Or has run_loop 2.2.3 not been included in this Calabash release?

Thanks very much for your work.

**Comment by jmoody** [comment]
Run-loop 2.2.3 has been released. 

This does not require a Calabash 0.20.4 release.

https://github.com/calabash/calabash-ios/wiki/Updating-your-run-loop-version
