### ISSUE TITLE
Swipe UIPickerColumnView is not working on XCode8

### ISSUE THREAD

**Issue by xiannicolae** [calabash/calabash-ios#1183]
Hi,

I am using the following command:
swipe(:up, {:query => "UIPickerColumnView index:0 label"})

Both swipe :up and :down are swiping the picker to the top.

Is it an issue or there is an alternative to swipe a picker column?

Thank you!

**Comment by jmoody** [comment]
@xiannicolae 

There is no good alternative gesture-based solution except maybe the `pan_coordinates` method.

http://calabashapi.xamarin.com/ios/Calabash/Cucumber/Core.html#pan_coordinates-instance_method

A programmatic solution would be:

```
query("UIPickerView index:0", {:selectRow => 5 :inComponent => 0 :animated => true})
```

I wrote that snippet from memory so it might be incorrect.   In English, "Call the Objective-C method `selectRow:inComponent:animated:` on the first UIPickerView".

The down side is that no UIPickerViewDelegate methods will be called.  If you need/want delegate methods to be trigger, please create an issue on https://github.com/calabash/calabash-ios-server - this is something that I have wanted since I started using Calabash and there has been renewed interest in programmatically triggering delegate methods.

**Comment by xiannicolae** [comment]
@jmoody Thank you for your feedback.

I will try the pan method or it just poped-in my mind another idea to create a swipe method where I am always selecting the last visibile element from the picker (when swiping up and the opposite for :down). Which do you think it would be the best approach in a professional way?

Thanks again!

**Comment by xiannicolae** [comment]
I created the following method which works the same as `swipe` before, but it doesn't look too professional tho:

```
def swiper_picker(dir, uiquery)
  case dir
  when :up
    tap_mark uiquery[-1]
  when :down
    tap_mark uiquery[0]
  end
  sleep(0.2)
end
```

Any tips to make it looks good will be great appreciated. Thank you!

**Comment by jmoody** [comment]
What is the `uiquery` argument?

And what is `uiquery[-1]`?

**Comment by xiannicolae** [comment]
Hi @jmoody,

I think that I didn't choose the var name too good. 

`uiquery` is expecting an `array` of the visibile picker's elements.

When I `swipe :up`, I am selecting the last visible element of the picker (`uiquery[-1]`), and when `swipe :down`, I select the first visible element of the picker (`uiquery[0]`).

And I am calling the method like this: 
`swipe_picker(:up, query("UIPickerColumnView index:0 label", :text))`

I know is not a gesture, but the outcome is identical to `swipe(:up, {:query => "UIPickerColumnView index:0 label"})`.

I tried its functionality on a single column picker, date picker (3 columns) with different values and worked 100%. Also I included a selection just after it (eg: `tap_mark selection`) and works as well, but only after I added the `sleep(0.2)` in the end.

Thank you!
