### ISSUE TITLE
Ambigiuous match of "I swipe left"

### ISSUE THREAD

**Issue by Tarek444** [calabash/calabash-ios#1241]
When I try to execute a left swipe with cucumber, the simulator doesn't even get opened, this is the response:

> Ambiguous match of "I swipe left":
> 
> calabash-cucumber-0.20.3/features/step_definitions/calabash_steps.rb:216:in `/^I swipe (left|right|up|down)$/'
> features/steps/login_steps.rb:41:in `/^I swipe left$/'

This is the step_definition: 
```
 Then /^I swipe (left|right|up|down)$/ do |dir|
   swipe(dir)
   sleep(STEP_PAUSE)
 end
```

**Comment by jmoody** [comment]
The error message explains exactly what the problem is:  there are two definitions of a Step - one in the Calabash predefined steps and on in `features/steps/login_steps.rb`.

You have two options:

1. remove your definition
2. stop importing predefined steps (recommended)

Read the code comment in this file:

https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/features-skeleton/support/env.rb

**Comment by Niko489** [comment]
https://app.cucumber.pro/projects/cucumber-ruby/documents/branch/master/features/docs/defining_steps/ambiguous_steps.feature
