### ISSUE TITLE
Querying webviews results in timeouts

### ISSUE THREAD

**Issue by renatorodrigues** [calabash/calabash-ios#550]
I'm using Calabash 0.11.0 and testing on the iPad Retina 8.0 simulator and most of my tests that perform queries on webviews are returning the following error:
`
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)`

Any idea of what is causing this?

**Comment by jmoody** [comment]
Closing.  The information here is condensed in this HotTopic.

https://github.com/calabash/calabash-ios/wiki/Hot-Topics#1-nslog-output-can-cause-apps-to-become-unresponsive-during-testing

**Comment by skhanam** [comment]
hi there, 
am seeing the timeout errors its not even the web view its native 

 @sanity @reinstall
  Scenario: Obtaining more information         # features/01signin.feature:5
    Given I am on the first experience screen  # features/step_definitions/signin_steps.rb:1
      Timeout waiting for elements:  (Calabash::Cucumber::WaitHelpers::WaitError)
      ./features/step_definitions/signin_steps.rb:3:in `/^I am on the first experience screen$/'
      features/01signin.feature:6:in `Given I am on the first experience screen'

am on Xcode 7.3 iOS 9.3 calabash 0.18.2 can someone tell why am encountering this issue

**Comment by jmoody** [comment]
@skhanam 

> am seeing the timeout errors its not even the web view its native

Why did you post this here?  The title of the issue is WebView.  How is this related to your app, which is native?  This issue is also closed and nearly a year old.

Please post your question on Stack Overflow or one the Calabash iOS forum.

Include more details in your post.  We have to _see the step definition_ - the short answer to your question is that view you are waiting for is not visible.

**Comment by skhanam** [comment]
@jmoody  i stumbled upon this issue while searching for similar issues. hence posted. i think it would be worth disabling comments .. have brought it up on forums. hope to see a  reply from experts
