### ISSUE TITLE
Does not contain a compatible architecture for target device.   Expected 'i386' but found ["x86_64"]

### ISSUE THREAD

**Issue by mohjay** [calabash/calabash-ios#665]
Hi,

I have installed calabash running with cocoapods. When I run `cucumber` I get the following:

```
does not contain a compatible architecture for target device.
  Expected 'i386' but found ["x86_64"]. (RunLoop::IncompatibleArchitecture)
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.0/lib/run_loop/lipo.rb:71:in `expect_compatible_arch'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.0/lib/run_loop/core.rb:119:in `expect_compatible_simulator_architecture'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.0/lib/run_loop/core.rb:214:in `run_with_options'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.0/lib/run_loop/core.rb:793:in `run'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:737:in `block in new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:735:in `times'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:735:in `new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:610:in `relaunch'
```
I have tried to play around with my Build Settings and setting the Build Active Architecture to YES/NO but no love. 

Architectures - `armv7, arm64`
Valid Architectures - `armv7, armv7s, arm64`

Also I can run the Target from XCode (6.1.1) without problems.

Thoughts?

**Comment by jmoody** [comment]
@mohjay 

Can you update your original post with your configuration details? 

* https://github.com/calabash/calabash-ios/wiki#reporting-problems

> I have tried to play around with my Build Settings and setting the Build Active Architecture to YES/NO but no love.

It is likely that updating your settings _did_ work, but the target on your simulator was not updated when you built with Xcode.

Try resetting the simulator (which uninstalls 3rd-party apps) and trying again.

```
$ be calabash-ios sim reset
```
>  have installed calabash running with cocoapods.

This *might* be causing a problem - CocoaPods uses .xcconfig configuration files which may or may not overwrite your Xcode build settings.

> Also I can run the Target from XCode (6.1.1) without problems.

Just to be clear, you are a seeing this error because the .app you are trying to install is incompatible with the simulator you are trying to install on.  You can either generate an app that is compatible with the target simulator or you can change simulators.

See **When targeting a Simulator, the app launches, then quits several times in rapid succession** 

- [wiki](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#1-when-targeting-a-simulator-the-app-launches-then-quits-several-times-in-rapid-succession)
- [gist](https://gist.github.com/jmoody/7543629290b7e192a261)

**Comment by mohjay** [comment]
Thanks @jmoody. As per the good bug reporting:

xcode-select path
`/Applications/Xcode.app/Contents/Developer`

version
`Xcode 6.1.1`
`Build version 6A2008a`

calabash version
`0.12.0`
```

Tried the reset but that didn't work.I also tried to manually set the SDK_VERSION to 8.1 but that didn't work either. The app also seems to build in the right directory `~/Library/Developer/Xcode/DerivedData/??-xyz/Build/Products/Debug-iphonesimulator/??-cal.app`

Is there a way to force calabash to look for the 64bit architecture?

**Comment by jmoody** [comment]
> As per the good bug reporting:

Perfect, thanks.

> Is there a way to force calabash to look for the 64bit architecture?

If you run cucumber with:

```
$ DEBUG=1 cucumber
```

You will see the .app that calabash is asking instruments to install.  You will also see the target simulator. The problem is the executable in the .app bundle is not compatible with the simulator.

#### Example

```
{
  :app => "/Users/moody/git/animated-happiness/chou/chou-cal.app",
  <snip>
  :device_target => "iPhone 5 (8.1 Simulator)",
  <snip>
}
```

You can use lipo to check what architectures are included (replace ?? as appropriate) in your ??.app/< executable >.

```
$ xcrun lipo -info ~/Library/Developer/Xcode/DerivedData/??-xyz/Build/Products/Debug-iphonesimulator/??-cal.app/?? 
```

Your ??.app/?? is reporting it contains only a x86_64 slice.  The default simulator is iPhone 5, which requires an i386 slice.  [code comment](https://github.com/calabash/run_loop/blob/develop/lib/run_loop/lipo.rb#L25).

You can point calabash to an .app and tell calabash to launch a specific simulator.  It is up to you to ensure that .app is compatible with the simulator.

```
$ APP=/a/path/to/Your.app DEVICE_TARGET=<some simulator> cucumber
```

Since your .app appears to be x86_64, you could change the DEVICE_TARGET to one of the x86_64 simulators.

```
DEVICE_TARGET="iPhone 5s (8.1 Simulator)" cucumber
```

Or you could build from Xcode targeting the iPhone 5 (not iPhone 5s) simulator.

If you have updated your Xcode build settings as suggested in the Hot Topic and you still cannot generate a FAT library, the problem is likely in the .xcconfig files that CocoaPods manages.

**Comment by mohjay** [comment]
Got it working by building the app with the iPhone5 simulator to generate the 32Bit binaries.

Thanks @jmoody
