### ISSUE TITLE
Incorrect test configuration design in After step of 01_launch.rb

### ISSUE THREAD

**Issue by agileseph** [calabash/calabash-ios#677]
* [calabash-cucumber/features-skeleton/support/01_launch.rb](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/features-skeleton/support/01_launch.rb)

```
Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  unless @calabash_launcher.calabash_no_launch?
    @calabash_launcher.relaunch
    @calabash_launcher.calabash_notify(self)
  end
end

After do |scenario|
  unless @calabash_launcher.calabash_no_stop?
    calabash_exit
    if @calabash_launcher.active?
      @calabash_launcher.stop
    end
  end
end
```

Issue:
1) Why is required '@calabash_launcher.stop' in After Step section, by implicit usage (explicitly, it's required to define NO_STOP env option)? Actually, the method means: 

```
# @!visibility private
def stop
  RunLoop.stop(run_loop) if run_loop && run_loop[:pid]
end
```
it means that it will be re-run loop with Instruments process

and

```
# RunLoop::Core 
def self.stop(run_loop, out=Dir.pwd)
  return if run_loop.nil?
  results_dir = run_loop[:results_dir]
  dest = out

  RunLoop::Instruments.new.kill_instruments

  FileUtils.mkdir_p(dest)
  if results_dir
    pngs = Dir.glob(File.join(results_dir, 'Run 1', '*.png'))
  else
    pngs = []
  end
  FileUtils.cp(pngs, dest) if pngs and pngs.length > 0
end
```

2) In Before Step section:

```
unless @calabash_launcher.calabash_no_launch?
    @calabash_launcher.relaunch
```

it's OK.

and

```
Calabash::Cucumber::Launcher
def relaunch(args={})
    #TODO stopping is currently broken, but this works anyway because instruments stop the process before relaunching
    RunLoop.stop(run_loop) if run_loop'
```

3) '@calabash_launcher.stop' produces errors of incorrect app work finish. So if you restart app you will have Alert Message.

4) In General, what are cases when we might re-run loop with Instruments during one Test Run of Test Suite?

5) Extra info related to exit processing: https://github.com/calabash/calabash-ios-server/blob/947805e43629afcfa26f7663c5f3bc047369b80f/calabash/Classes/FranklyServer/Routes/LPExitRoute.m

**Comment by TeresaP** [comment]
4. If I understand your question correctly, we do have some cases where we have had to uninstall and reinstall the app during the test run. We have also had to kill and restart the app.

**Comment by jmoody** [comment]
@agileseph 

I appreciate the questions, but in the future could you use GitHub Markdown to format your text?  I had to spend time adding formatting to your post in order to understand your questions.

I think your questions boil down to, "When would I ever want to use `NO_STOP`?"

There is a great example in the Calabash iOS API docs [1].

If you don't want your app to quit after cucumber is finished running your tests, set NO_STOP=1.

Again, see the docs [1] for an example workflow that uses `NO_STOP`.

You mention "re-run loop" several times.  To clarify, a new run-loop is created every time `cucumber` or `start_test_server_in_background` is called.

The only time a run-loop is ever "reused" is when calling:

```
> console_attach
```

in the Calabash console.  This is not really a "reuse"; we attach to the already running instruments process so you can start interacting with the app from the console at the point where your tests stopped.


> 3) '@calabash_launcher.stop' produces errors of incorrect app work finish. So if you restart app you will have Alert Message.

This is troubling.  Can you paste your configuration details and the error you are seeing?


#### Other Hooks

I want to stress that these are _suggested_ hooks.  Here are some examples of other hooks:

* briar-ios-example [01_launch.rb](https://github.com/jmoody/briar-ios-example/blob/master/Briar/features/support/01_launch.rb)

```
require 'calabash-cucumber/launcher'

Before do |scenario|
  launcher = Calabash::Cucumber::Launcher.new
  launcher.relaunch
  launcher.calabash_notify(self)
end

After do |scenario|
  calabash_exit
end

at_exit do
  # do nothing
end
```


#### Links

- [1] [NO_STOP](http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#NO_STOP)

**Comment by agileseph** [comment]
Thank you, @jmoody 
As I understand from the code above:
1) 'calabash_exit' is used to close iOS app; - it's OK.
2) 'launcher.stop' is used to kill instruments; - for what cases it's required 'launcher.stop' method during Suite Run? Is it required to use both methods as 'calabash_exit' and 'launcher.stop' to finish app work and restart app?

**Comment by jmoody** [comment]
> 2) launcher.stop - is used to kill instruments; 
> For what cases it's required 'launcher.stop' method during Suite Run? 

It is never required call `launcher.stop`.  

> Is it required to use both methods as 'calabash_exit' and 'launcher.stop' (~ kill the Instruments) to finish app work and restart app?

The short answer is:  no.  It is not necessary to call `launcher.stop` and `calabash_exit`.  We recommend calling `calabash_exit` because it attempts to shutdown the app in a graceful way.

> Is it workable the simplest case of launch config as the following example:

```
Before do |scenario|
  start_test_server_in_background
end
```

Don't use `start_test_server_in_background` in your hooks; use this only in the console.

Use this pattern instead.

```
Before do |scenario|
   launcher = Calabash::Cucumber::Launcher.new
   launcher.relauch
   launcher.calabash_notify(self)   
end
```

**Comment by jmoody** [comment]
@agileseph I am going to close this because it is more a question that a feature request or bug report.
