### ISSUE TITLE
Can we query the server for information about UIImage?

### ISSUE THREAD

**Issue by iMerica** [calabash/calabash-ios#706]
Hey guys, I have an image here:

```ruby
query('*').select{|x| x['class'] == 'UIImageView'}[1]
# => 
{"alpha"=>1,
 "enabled"=>false,
 "id"=>"Foobar",
 "visible"=>1,
 "frame"=>{"y"=>0, "x"=>0, "width"=>18.5, "height"=>18.5},
 "accessibilityElement"=>0,
 "class"=>"UIImageView",
 "label"=>nil,
 "value"=>nil,
 "rect"=>{"y"=>250.5, "height"=>18.5, "center_y"=>259.75, "x"=>186.5, "center_x"=>195.75, "width"=>18.5},
 "description"=>"<UIImageView: 0x7fc31ae96780; frame = (0 0; 18.5 18.5); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fc31b5405e0>> - (null)"}
```
I'd like to get an MD5 checksum on the file like:
```ruby
require 'digest/md5'

a = query('*').select{|x| x['class'] == 'UIImageView'}[1]
Digest::MD5.file(a.file_handle) # file_handle doesn't exist
```
How can I refer to an image's file handle or location?
Is this within the scope of Calabash? Or Instruments?

**Comment by jmoody** [comment]
@iMerica 

In your example, you are asking for the value of the `class` key which is the string `"UIImageView"`.

You would have to query like this:

```
# On every UIImageView, call the ObjC selector `image`.
query('imageView', :image)
```

We cannot automatically return a file path for a couple reasons:

1. Sometimes the `UIImage` will not be backed by file; you can create UIImage in code.
2. If it is backed a file, it might be on a physical device and we cannot pull files from devices.

We could try to return a checksum of some kind, but I don't think we could guarantee a stable fingerprint because often checksums can depend on local settings.

We might be able to return a blob of data or push the image to AWS, but I am not sure.

Pull-requests welcome.

**Comment by iMerica** [comment]
Thanks for your help @jmoody!

I'll continue to look into this. I might even be able to leverage [backdoor()](http://calabashapi.xamarin.com/ios/Calabash/Cucumber/Core.html#backdoor-instance_method) by invoking an objective C method that does this work for me and returns the results on calabash side. [Like this](http://stackoverflow.com/questions/1684799/generate-hash-from-uiimage)
