### ISSUE TITLE
Get the evidence as video/movie in Calabash

### ISSUE THREAD

**Issue by hoangvm** [calabash/calabash-ios#867]
I am a newbie of Calabash ( Automation Testing tool) .

Regrading the evidence with calabash, as far as I know we just can take a picture/screenshot only.
However with some special function/input I'd like to record a video to confirm the inputting/tranferring screen...
Can we do the generate evidence as video with Calabash ?
Please help me if you know... 
Thank you so much

Here is information in my environment: 

```
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer/

$ xcodebuild -version
Xcode 6.4
Build version 6E35b

$ calabash-ios version
0.15.0

$  curl http://localhost:37265/version
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>
```

**Comment by jmoody** [comment]
There is no way to record a video.  I am not sure we could ever add this feature because it would require that we and our end users add an AV framework to their build.  We want to keep the number of server dependencies at a minimum.

This is might be a good use case for a Calabash plug-in and a custom Calabash server route.  Unfortunately, I don't have any time to invest in this.  An example of a Calabash plug-in can be found here: https://github.com/calabash/memoryPluginCalabash - but it is woefully inadequate.

There are no examples of custom routes.

If you are interested, I could invest a little time getting you started.

**Comment by hoangvm** [comment]
Dear Joshua

Thank you for your reply.
I understood the situation with calabash IOS.
I will investigate in sometime and report you if have any news ( maybe no
:) )
Anyway, thank you so much !

Regards,
Hoang

*****************************************************
  *Vu Minh Hoang* （ヴー ･ ミン ･ ホアン）

  *Mobile * (+81)80-4943-1987 - Japan
  *Skype *: vm.hoang
  *Email *: hoangvmh@gmail.com

*****************************************************

**Comment by sleekweasel** [comment]
You can record the simulator - I tried setting it up, but had to abandon it because we're testing with parallel_calabash and QuickTime can only record the main desktop.

I've put a gist up:

https://gist.github.com/sleekweasel/1aee7b339f3f6319dda0

**Comment by TeresaP** [comment]
@sleekweasel That is really cool. Thank you for sharing!

**Comment by jmoody** [comment]
The Xamarin Test Cloud has support for video capture - playback your tests at a movie.
