### ISSUE TITLE
Calabash automation for iOS app build using Swift and objective C

### ISSUE THREAD

**Issue by sudha-raman** [calabash/calabash-ios#870]
We are trying to implement calabash-setup for iOS app build using Swift and objective C. When we are running the initial setup, its ended with following error.

Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: 
  
  "Timed out waiting for UIAutomation run-loop Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError.
  
  Logfile: /var/folders/c3/xxd6j_9n7_sg_3w8x10c6zw00000gp/T/run_loop20151008-22794-1jmq35e/run_loop.out
  
  Waiting for device to boot...
  
  
   (Calabash::Cucumber::Launcher::StartError)
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:778:in `new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch'

We have tried all the options available in online community to resolve, no luck for us. Finally app got invoked successfully after removing the SWIFT code.

Could you please confirm whether calabash-ios will work on app build using SWIFT and Objective C.

**Comment by jmoody** [comment]
@sudha-raman I believe you posted this question in several places.  If so, please refrain from doing this.  There is really just me answering questions - cross-posting slows me down.  Please be patient.

> Could you please confirm whether calabash-ios will work on app build using SWIFT and Objective C.

Yes.  Calabash will work with Swift and Objective-C.  Period.  There are no issues using Calabash with Swift.

My guess is that you have Watch extension in your app and that you used `calabash setup`.  This is broken.

Tracking this issue here:

**Calabash builds/runs Apple Watch app instead of iPhone app** #832

**Comment by jmoody** [comment]
Please reopen or @mention me if you are still having problems.

**Comment by jmoody** [comment]
I have released run_loop 2.0.10.pre1 which might resolve the FIFO problems.  Thanks @TeresaP
