### ISSUE TITLE
[Query] Relaunch of application within a scenario (with backdoor to clear all NSUserDefaults)

### ISSUE THREAD

**Issue by tommeier** [calabash/calabash-ios#932]
Hi @jmoody , 

Not sure if this is an issue for anyone else, but I have a scenario where i relaunch the application within a scenario itself (to ensure app initial boot steps aren't triggered after first load).

However, I've recently added some backdoors to completely wipe the NSUserDefaults from within a scenario and noticing odd behaviour, it looks like:

  - launch scenario
  - run steps
  - run step for clearing data backdoor
  - run further steps that change NSUserDefaults
  - run relaunch within scenario
  - on relaunch the further steps after clearing data are now missing, and looks like a fresh launch again?

Are there special keys made by Calabash within NSUserDefaults that would cause this if cleared for the bundle identifier domain?

 - This is just a query though, running `@launcher.relaunch` within a scenario works perfectly if I _don't_ use a backdoor wiping preferences within the scenario. I was just testing this to avoid the slow reboot of the simulator, which is possibly resolved in the next release to include (https://github.com/calabash/calabash-ios/pull/923/files)

Thanks,

**Comment by jmoody** [comment]
If you wipe NSUserDefaults, then you won't be able to use the `:preferences` UIA strategy.  The `:preferences` strategy is preferred because it is fast and stable.  Unfortunately, Apple breaks the UIAutomation Preferences API all the time.  To support iOS 9, we had to drop our `:preferences` support in the 0.16.x releases. `:host` is the default for Xcode 7; which is too bad because `:host` is slow and can be unstable.

Starting in 0.17.x preferences will be available to use on simulators and _devices_ (broken by Apple since Xcode 6, fixed in Xcode 7).  This will be opt-in behavior for the first few releases of 0.17.x; we need a larger pool of testers.

I recommend that you try the `:shared_element` strategy for the Scenario you are describing.  It does not depend on NSUserDefaults, it is as fast as `:preferences`, and as stable.   `:shared_element` does has some limitations - there are some open issues sprinkled around about this.  

I would use a Before + a tag and set the strategy.

You'll forgive my hasty example:

```ruby

Before("@reset_defaults") do
  @strategy = :shared_element
end

Before do
  options = {
     # A nil value will force the default behavior (:host at the moment)
     :uia_strategy => @strategy
  }

  <launcher instance>.relaunch(options)
  @strategy = nil
end
```

**Comment by tommeier** [comment]
Fantastic! Thanks @jmoody , i'll try that out :smiley:

**Comment by tommeier** [comment]
FYI: works perfectly for this scenario!
