### ISSUE TITLE
screenshot path relative to out directory is incorrect

### ISSUE THREAD

**Issue by joshes** [calabash/calabash-ios#94]
When setting the --out flag the screenshot_and_embed doesn't "embed" the path correctly.

Consider:

``` sh
export SCREENSHOT_PATH=report/
cucumber --format html --out report/index.html
```

The image HTML references: 

``` html
<img src="report/myimage.png"/>
```

Whereas it should be relative to the "out" directory:

``` html
<img src="myimage.png"/>
```

For now I leave the screenshot_path unset and move the images in bulk in the "at exit" hook which is fine, but is quite hacky.

Looking into possible fixes, it seems we need to check and modify the embed path (result from screenshot) before embedding. I'm fine with doing this myself, but wanted to bounce the idea first.

Thanks.

**Comment by aikhelis** [comment]
Good option is to embed Base64-encoded images into HTML rather than linking to a disk location. This increases file size a bit, but is less flaky. Does calabash support that with its screenshots API?

http://stackoverflow.com/questions/6229071/cucumber-embed-for-screenshots-not-linking-to-screenshot
