### ISSUE TITLE
Failed to locate key error on systems with more than one language

### ISSUE THREAD

**Issue by stopiccot** [calabash/calabash-ios#965]
On systems with more than one language you sometimes get error:

    Could not type 'mmmmmm'  - UIAutomation returned an error: 'VerboseError: target.frontMostApp().keyboard() failed to locate key 'm'' (RuntimeError)

I've noticed that this is caused by the fact that for some reason simulator switches to second language (russian in my case).  App fails to find 'm' letter. Than I guess it "assumes" that it failed to find 'm' letter because it's in numeric mode. So it tries to get to letter keyboard by pressing left-bottom button. Instead it actually gets to numeric keyboard. After some switching from russian to numeric and back to russian it fails with mentioned error. So my obvious idea is that it would be great if runtime could ensure english keyboard in simulator.

Everything was tested with calabash-ios 0.17 (both ruby gem and calabash.framework)

**Comment by jmoody** [comment]
Changing locales and languages has been broken since Xcode 6.0.

On the simulators, we will be fixing this in the near future.

For a proof of concept, you can see this example:

* https://github.com/calabash/Permissions/blob/master/.irbrc#L134
* https://github.com/calabash/Permissions/blob/master/features/0x/support/01_launch.rb#L78

Alternatively, you can detect the language of the keyboard by querying for the text of the space bar.  If it is not English, you can switch languages by touching the "International" button.

**Comment by jmoody** [comment]
@stopiccot 

Soon you will be able to set the preferred language:

```ruby
   target = ENV["DEVICE_TARGET"] || RunLoop::Core.default_simulator

    simulator = RunLoop::Device.device_with_identifier(target)

    RunLoop::CoreSimulator.set_language(simulator, "de")
```

We will have examples and a command-line interface.

On Xcode 6, you will need launch with args:

```ruby
options = {
  :args =>  ["-AppleLanguages", "(ru)", "-AppleLocale", "ru"]
}
launcher.relaunch(options)
```

On Xcode 7, you will not need to launch with args.  Not sure why...

Do you think this will help?

**Comment by jmoody** [comment]
@stopiccot 

Please reopen if the new `calabash-ios sim locale` tool is not working for you.

https://github.com/calabash/calabash-ios/wiki/Changing-Locale-and-Language
