### ISSUE TITLE
. Error: VerboseError: Unable to tap-offset

### ISSUE THREAD

**Issue by Geetyty** [calabash/calabash-ios#983]
While executing the tests on the iOS 8 devices, we are seeing the below error while touching elements.

```
uia action failed because: Input: uia.tapOffset('{:x 372.41, :y 709.52}')
      . Error: VerboseError: Unable to tap-offset: {:y 709.52, :x 372.41}  [native code] fail__delegate@file:///Users/jenkins/workspace/CalabashDevelop_Device_iPhone6/Calabash/4F62EADE-CDE2-40EA-81D8-D010831CAB97/_run_loop.js:25616:20
```

Could you please help provide any pointers how to get this resolved

**Comment by jmoody** [comment]
Please update your question with the following information:

* https://github.com/calabash/calabash-ios/wiki#reporting-problems

What are you trying to touch?  Is it reproducible all the time?

**Comment by Geetyty** [comment]
Here is my mac's information:
# xcode installation location
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

# xcode version
$ xcodebuild -version
Xcode 6.4
Build version 6E35b

# calabash version
$ calabash-ios version
0.17.1

# start your app manually in the simulator or from Xcode
$ curl http://localhost:37265/version
curl: (7) Failed to connect to localhost port 37265: Connection refused
=====================================================
When I touch some buttons in app on my physical device,I can see this issue.

**Comment by jmoody** [comment]
@Geetyty 

We really need to see the Calabash server version that is embedded in your app.

> curl: (7) Failed to connect to localhost port 37265: Connection refused

You need to use the IP address of your physical device.  The "failed to connect" tells me that you have not linked your app to Calabash. 

I also see that you are running in Jenkins.  There are many problems running on Jenkins.

I don't like answering questions about Jenkins setups because there are many many things that could be wrong in your setup.  With that said, we test Calabash iOS and Android nightly and on GitHub activity with Jenkins so there is at least one valid Jenkins configuration. :8ball: 

Before your tests start, try:

```
$ be run-loop simctl manage-processes
```

This will try to kill and/or restart the CoreSimulator processes.  This improved stability for us.

You can can also call:

```
RunLoop::CoreSimulator.terminate_core_simulator_processes
```

from within Ruby before your test suite starts.  Don't run this before/after every Scenario.

**Comment by jmoody** [comment]
@Geetyty Please comment here if you are still having this issue.
