### ISSUE TITLE
Pre-defined cucumbers not found when running `cucumber -d`

### ISSUE THREAD

**Issue by sapieneptus** [calabash/calabash-ios#986]
@jmoody [ref](https://github.com/xamarin/test-cloud-frontend/issues/2017)

It seems this can be resolved by a `require 'calabash-cucumber/calabash_steps'`, but if that's the real solution, this should probably be addressed in the `calabash-ios gen` utility.

**Comment by jmoody** [comment]
Now I think it might be related to the cucumber version.

Any chance you can run with `gem "cucumber", "~> 1.3"`?

**Comment by sapieneptus** [comment]
Current `cucumber` is  1.3.20, same results

**Comment by jmoody** [comment]
@sapieneptus Where did you add the `require "calabash-cucumber/calabash_steps"`

**Comment by jmoody** [comment]
@sapieneptus @krukow @chawang

There is no way to handle this problem; any change we make will cause problems for users regardless of whether or not they use predefined steps.

Since -d does not load the features/support/env.rb, the predefined steps are not available.

The way to solve this problem is to add a dry run file:

```
# features/support/dry_run.rb
require "calabash-cucumber"
require "calabash-cucumber/calabash_steps"
```

I will make a note in the features/support/dry_run.rb file that is created by `gen`.

**Comment by krukow** [comment]
What about 

```
# features/step_definitions/calabash_steps.rb
```
that's what it is

**Comment by jmoody** [comment]
I took a stab at programmatically detecting that the user wants to use predefined steps (see the PR).

@krukow I am not sure what you mean.

**Comment by krukow** [comment]
@jmoody I don't want this file: `features/support/dry_run.rb`

i want this file:  `features/step_definitions/calabash_steps.rb` 

put step definitions in the `step_definitions` folder - make sense?

**Comment by jmoody** [comment]
I want to keep the `gen` behavior as simple as possible and still support both cases: 

1. wants predefined steps (default)
2. does not want predefined steps - requires editing the `support/env.rb` file.

I don't want to add features/step_definitions/calabash_steps.rb to the skeleton since it is not necessary (already included in AfterConfiguration of cucumber.rb) and is not something we have done in the past.

If we don't use dry_run, then I don't want to change anything.  User's who encounter this problem on the XTC or anywhere else can add a dry_run or the calabash_steps to their project.

> I don't want this file:

The `dry_run` file already exists in the skeleton.  Are you saying you don't want that file at all?

**Comment by krukow** [comment]
discussed on slack - I'm reverting my comments - go @jmoody
